config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :essays

  get 'disgapear/index'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get    'logout'  => 'sessions#destroy'
  post 'essays/:id' => 'essays#update'

  root 'disgapear#index'

end

app/models/essay.rb
class Essay < ActiveRecord::Base
	validates :topic, :description, :content, :word_limit, presence: true
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
	has_many :essays

	include BCrypt
  validates :email,  uniqueness: true, presence: true, length: { maximum: 50 }

  has_secure_password
  validates :password, presence: true, length: { minimum: 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/disgapear_controller.rb
class DisgapearController < ApplicationController
  def index
  end
end

app/controllers/essays_controller.rb
class EssaysController < ApplicationController
	def index
	end

	def new
		@essay = Essay.new
	end

	def create
    @essay = Essay.new(essay_params)
    @essay.user_id = current_user.id
    respond_to do |format|
      if @essay.save
        # session[:essay_id] = @essay.id
        format.html { redirect_to essay_path(@essay), notice: 'Essay was successfully created.' }
        format.json { render :show, status: :created, location: @essay }
        # redirect_to root_path
      else
        flash[:danger] = @essay.errors.full_messages.to_sentence
        format.html { render :new }
        format.json { render json: @essay.errors, status: :unprocessable_entity }

        # render 'new'
      end
    end
  end

	def show
		@essay= Essay.find(params[:id])
    @user= User.find(@essay.user_id)
	end

  def edit
    p "+++++++"
    @essay=Essay.find(params[:id])
  end

  def update
    @essay= Essay.find(params[:id])
    @essay.revision = params[:essay][:revision]
    @essay.save
    redirect_to essay_path(@essay)
  end

	private

	def essay_params
    params.require(:essay).permit(:user_id, :topic, :description, :content,:word_limit)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to disgapear_index_path
    else
      flash[:danger] = "Invalid combination"
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to root_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
        # redirect_to root_path
      else
        flash[:danger] = @user.errors.full_messages.to_sentence
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }

        # render 'new'
      end
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email,:password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def logged_in
    session[:user_id] ? true : false
  end

  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
end

app/helpers/disgapear_helper.rb
module DisgapearHelper
end

app/helpers/essays_helper.rb
module EssaysHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/disgapear/index.html.haml
.site-wrapper
	%img.img{:src => "../notepencoffee.jpeg"}/
	.site-wrapper-inner
		.cover-container
			.masthead.clearfix
				.inner
					%nav.navbar.navbar-inverse.navbar-fixed-top
						.container
							.navbar-header
								%button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
									%span.sr-only Toggle navigation
									%span.icon-bar
									%span.icon-bar
									%span.icon-bar
								%a.navbar-brand{:href => "/"}
									%img.brand{:src => "logowhite.png"}
							#navbar.collapse.navbar-collapse
								%ul.nav.navbar-nav.pull-right
									%li
										%a{:href => "/"} Home
									%li
										%a{:href => "#about"} About
									-if logged_in
										%li
											%a{:href => "/logout"} Sign out
									-else
										%li
											%a{:href => "/login"} Sign in
			.inner.cover
				%img{:src => "logoblack.png"}
				%h1.cover-heading Disgapear
				%p.lead Disgapear is an online essay editing service. We hope to break down language barriers and narrow down cultural divides for those who are not English native speakers.
				%p.lead
					-if logged_in
						%a.btn.btn-lg.btn-default{:href => new_essay_path} Send your essay
					-else
						%a.btn.btn-lg.btn-default{:href => login_path} Send your essay
			.mastfoot
				.inner
					%p
						%span.glyphicon.glyphicon-copyright-mark{"aria-hidden" => "true"}>Disgapear. Inc.

app/views/essays/edit.html.haml
%div.container 
  = form_for :essay, url: essay_path(@essay.id)do |f|
    .form-group
      = f.label :topic
      %br
      = f.text_field :topic, class: 'form-control', disabled: "disabled"

    .form-group
      = f.label :description
      %br
      = f.text_field :description, class: 'form-control', disabled: "disabled"
    .form-group
      = f.label :content
      %br
      = f.text_area :content, class: 'form-control', disabled: "disabled"

    .form-group
      = f.label :revision
      %br
      = f.text_area :revision, class: 'form-control'

    .form-group
      = f.label :words_limit
      %br
      = f.number_field :word_limit, class: 'form-control', disabled: "disabled"
    
    .form-group
      = f.submit :'submit', class: 'btn btn-success'

app/views/essays/index.html.haml
%h1 hi

app/views/essays/new.html.haml
%div.container 
	= form_for :essay, url: essays_path do |f|
		- if @essay.errors.any?
			- flash.each do |message_type, message|
				%div{:class => "alert alert-#{message_type}"}= message

		.form-group
			= f.label :topic
			%br
			= f.text_field :topic, class: 'form-control', placeholder: "What are you most excited about or looking forward to in your college experience?"

		.form-group
			= f.label :description
			%br
			= f.text_field :description, class: 'form-control', placeholder: "Personal statement for Harvard University"
		.form-group
			= f.label :content
			%br
			= f.text_area :content, class: 'form-control'

		.form-group
			= f.label :words_limit
			%br
			= f.number_field :word_limit, class: 'form-control', placeholder: 150
		
		.form-group
			= f.submit :'submit', class: 'btn btn-success'

app/views/essays/show.html.haml
%div.container 
  %table.table
    %tbody
      %tr
        %th{:scope => "row"} Topic
        %td
          =@essay.topic
      %tr
        %th{:scope => "row"} Content
        %td
          =@essay.content

      %tr
        %th{:scope => "row"} Revision
        %td
          =@essay.revision
              
      %tr
        %th{:scope => "row"} User name
        %td
          =@user.last_name         
      %tr
        %th{:scope => "row"} Description
        %td
          =@essay.description
      %tr
        %th{:scope => "row"} Word limit
        %td
          =@essay.word_limit


%div.container 
  .panel.panel-default
    / Default panel contents
    .panel-heading
      =@essay.topic
    .panel-body
      %p
        =@essay.content
    / List group
    %ul.list-group
      %li.list-group-item
        =@essay.revision
      %li.list-group-item 
        =@user.last_name
      %li.list-group-item
        =@essay.description
      %li.list-group-item
        =@essay.word_limit

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Disgapear</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="../../logoblack.png">

  <!-- Bootstrap core CSS -->
  <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">   
  <!-- ===========not useful??==================== -->

  <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
  <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="cover.css" rel="stylesheet">

  <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
  <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
  <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>



<body>

<%= yield %>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>

</body>
</html>

app/views/users/new.html.haml
%div.container
  = form_for :user, url: users_path do |f|

    - if @user.errors.any?
      - flash.each do |message_type, message|
        %div{:class => "alert alert-#{message_type}"}= message

    .form-group
      = f.label :first_name
      %br
      = f.text_field :first_name, class: 'form-control'


    .form-group
      = f.label :last_name
      %br
      = f.text_field :last_name, class: 'form-control'

    .form-group
      = f.label :email
      %br
      = f.text_field :email, class: 'form-control'

    .form-group
      = f.label :password
      %br
      = f.password_field :password, class: 'form-control'

    .form-group
      = f.label :confirm_password
      %br
      = f.password_field :confirm_password, class: 'form-control'

    .form-group
      = f.submit :'submit', class: 'btn btn-success'